// export const goodsList=[
//       {id:0,
//       type:"波奇饭",
//       right_item:[
//         {id:1,
//          dish:"波奇1",
//          dishRemark:"xdfefe",
//          dishPrice:"",
//          picURL:"/images/dishPic/苏州轻食拍摄0957.JPG"
//          qty:0},
//         {id:2,
//         dish:"波奇2",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:3,
//         dish:"波奇3",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:4,
//         dish:"波奇3",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:5,
//         dish:"波奇3",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:6,  
//         dish:"波奇3",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0}
//       ]},
//       {id:1,
//       type:"意面",
//       right_item:[
//         {id:0,
//         dish:"意面1",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:1,
//         dish:"意面2",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:2,
//         dish:"意面3",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0}
//       ]},
//       {id:2,
//       type:"沙拉",
//       right_item:[
//         {id:0,
//         dish:"沙拉1",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:1,
//         dish:"沙拉2",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:2,
//         dish:"沙拉3",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0}
//       ]},
//       {id:3,
//       type:"咖啡",
//       right_item:[
//         {id:0,
//         dish:"咖啡1",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:1,
//         dish:"咖啡2",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0},
//         {id:2,
//         dish:"咖啡3",
//         dishRemark:"xdfefe",
//         dishPrice:"",
//         picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
//         qty:0}
//       ]},
// ]

export const goodsList=[
    {id:0,
     dish:"波奇1",
     dishRemark:"xdfefe",
     dishPrice:"",
     type:"波奇",
     picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
     qty:0},
    {id:1,
    dish:"波奇2",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"波奇",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:2,
    dish:"波奇3",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"波奇",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:3,
    dish:"波奇3",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"波奇",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:4,
    dish:"波奇3",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"波奇",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:5,  
    dish:"波奇3",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"波奇",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:6,
    dish:"意面1",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"意面",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:7,
    dish:"意面2",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"意面",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:8,
    dish:"意面3",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"意面",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:9,
    dish:"沙拉1",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"沙拉",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:10,
    dish:"沙拉2",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"沙拉",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:11,
    dish:"沙拉3",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"沙拉",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:12,
    dish:"咖啡1",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"咖啡",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:13,
    dish:"咖啡2",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"咖啡",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0},
    {id:14,
    dish:"咖啡3",
    dishRemark:"xdfefe",
    dishPrice:"",
    type:"咖啡",
    picURL:"/images/dishPic/苏州轻食拍摄0957.JPG",
    qty:0}
]